### ISSUE TITLE
Transformer_res=np.load(root+"trans.npy") VAE_res = np.load(root+"VAE_res.npy") GAN_res = np.load(root+"GAN_res.npy")

### ISSUE THREAD

**Issue by notablefire** [Layout-Generation/layout-generation#10]
Excuse me, where are the three npy files? Thanks

**Comment by notablefire** [comment]
is there anybody?

**Comment by notablefire** [comment]
@tushar-jain01

**Comment by yashjain7856** [comment]
Hi @notablefire !
You can find all four files from the link below.
https://drive.google.com/drive/folders/138gCPlkU1KZopLxODBggl7clqQJmBLut?usp=sharing

**Comment by Jinyang228** [comment]
> Hi @notablefire ! You can find all four files from the link below. https://drive.google.com/drive/folders/138gCPlkU1KZopLxODBggl7clqQJmBLut?usp=sharing
> 
> I am also adding these files in the repo in the metrics section.

Thanks a million!
