### ISSUE TITLE
Reproduce Results for Layout Transformer

### ISSUE THREAD

**Issue by shanyang-me** [Layout-Generation/layout-generation#3]
Hi! I was following you code to reproduce the results for Layout Transformer. To get the results you show on the website, did you use the same setup as shown in the notebook? like batch_size = 1 and trained only with 10k examples for PubLayNet dataset?

**Comment by 23yashm** [comment]
Below is the detailed prediction plot for the trained model. The batch size is kept to be **1**.

![publay_1](https://user-images.githubusercontent.com/67385364/136769012-8673d6b3-ae81-4de7-8364-ed41cd22943c.png)

**Comment by mln00b** [comment]
Hi,
I'm trying to reproduce the LayoutTransformer results, just ran the notebook given, on the PubLayNet dataset, from the link given [here](https://github.com/Layout-Generation/layout-generation/issues/4#issuecomment-954498167)

However, my plot looks like this. What could be going wrong here?
![publay%2B99](https://user-images.githubusercontent.com/83297350/146739098-3d8fd7d0-d993-4703-80a1-ea737668e2b1.png)

**Comment by mln00b** [comment]
Could you share the rico & publaynet data file used for LayoutTransformer?
@yashjain7856 @tushar-jain01

**Comment by yashjain7856** [comment]
@mln00b Most probably the issue lies in your publaynet dataset as your ground truth is not satisfactory.
Refer to this comment for our processed PublayNet dataset : [Link](https://github.com/Layout-Generation/layout-generation/issues/4#issuecomment-954498167)
