### ISSUE TITLE
What is the format for the numpy file when loading data in LayoutVAE.py

### ISSUE THREAD

**Issue by sbunian** [Layout-Generation/layout-generation#4]
Hi,

  I am trying to run the main.py file inside LayoutVAE/Source folder. There is a load_data method inside layoutvae.py module. However, there is no information on the format of this file.

Can you please share some information regarding what format does this .npy file need to be in.

Thanks
Sara

**Comment by sbunian** [comment]
Hi Tushar,


   Thanks for the explanation. We downloaded the npy file you provided and were able to run through the code.

Would you be happy to please provide us the actual Python code used to generate this numpy file please?

Thanks
Sara

**Comment by sukritiverma1996** [comment]
Hey Tushar,
The paper says that number of elements goes upto 330k samples having a maximum of 128 elements for PubLayNet.
But the notebook has just 10k samples and length of 9.
How can we adjust the code for 128 samples? pad with zeros?

Thanks!
Sukriti

**Comment by tushar-jain01** [comment]
Hi Sukriti,
Padding with zero is a simpler option but it will have larger computational requirements so instead of using zeros I will suggest you to use loops this may take more time but you will not run out of memory. But you can use padding with zero if you don't have issue with memory.
